Finalized HTML of the SignUp page
AlanaPeres/Soft-Finance pull request #72
Opened 2023-03-29 02:07 UTC by luanaoliveira

2023-03-29 15:56 UTC, lbvargas99 requested changes
Separar por div cada campo do form, adicionar um span para que possa ser feito o placeholder com a animação

Os termos, precisa ter um checkbox, antes da label, e tem um botão no meio deles

Adicionar required nos campos obrigatórios

o UF, acho que poderia ser um select (definir com o grupo)

2023-04-03 13:58 UTC, lbvargas99 reviewed
Trocar o padrão de nomenclatura das classes por snake_case, no futuro pode vim a dar conflito utilizar classes com hífen, além de não ser uma prática recomendada do react.

Centralizar verticalmente a versão desktop

2023-04-03 14:37 UTC, LENNANrnz reviewed
- arrumar style modules para que o escopo global não seja afetado.

2023-04-03 22:03 UTC, LENNANrnz approved these changes

2023-04-03 22:04 UTC, merged