feat: adicionando modal de recuperacao de senha na pagina de login
AlanaPeres/Soft-Finance pull request #90
Opened 2023-04-03 21:18 UTC by LariLealDias

adicionando modal de recuperação de senha na pagina de login: mudando de rota (link to " ") para um button no html de login e criando estrutura de modais no diretório components

2023-04-03 22:49 UTC, LENNANrnz approved these changes

2023-04-04 11:09 UTC, lbvargas99 requested changes
Remover todos locais que possuem declaração de classe ou id com hífen.

2023-04-04 21:39 UTC, AlanaPeres approved these changes

2023-04-04 21:40 UTC, AlanaPeres approved these changes

2023-04-04 21:44 UTC, AlanaPeres approved these changes

2023-04-04 21:45 UTC, closed without merging